on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: 🚀 Deploy with Fito
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@master

      - name: GO!
        uses: dimaslz/dimaslz-Action@wip2
        with:
          server_ip: ${{ secrets.CONNECTION_HOST }}
          user: ${{ secrets.CONNECTION_USER }}
          ssh_private_key: ${{ secrets.CONNECTION_PRIVATE_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_host: dimaslz.dev
          app_name: preact-vite
          static: true
          # build_command: { { BUILD_COMMAND } }
          env: |
            NODE_ENV=production
            VITE_APP_TITLE="demo text from env"
